name: o projeto ativa
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: projeto de ativação das artes visuais na Bahia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#98dad3'
    - '#fa3500'
    - '#ffa366'
    - '#305d7b'
    - '#0ea7b5'
  brandStrength: 0.125
  lightness: 1
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
