name: o projeto ativa
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23391
title: projeto de ativação das artes visuais na Bahia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2c1a10'
    - '#935533'
    - '#fecf7e'
    - '#c89859'
  brandStrength: 0.0625
  lightness: 0.875
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
