name: o projeto ativa
favicon: null
layout_spectrum: 0
typography_spectrum: 0.99793
title: projeto de ativação das artes visuais na Bahia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#ffffff'
    - '#5e5d49'
    - '#a5d625'
    - '#afa993'
  brandStrength: 1
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
