name: o projeto ativa
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5624
title: projeto de ativação das artes visuais na Bahia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9c9c9c'
    - '#191919'
    - '#525962'
    - '#767c8a'
    - '#fae3d4'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
